# Generated by Django 4.1.2 on 2022-12-13 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlairUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=255
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("phone_number", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=255)),
                (
                    "traveled_within_last_two_weeks",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "travel_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experiencing_symptoms",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "specify_symptoms",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vaccine_card", models.ImageField(upload_to="uploads/vaccine_cards")),
                ("user_photo", models.ImageField(upload_to="uploads/student_images")),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "health_form_submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.flairuser",
                    ),
                ),
            ],
        ),
    ]
